CUSTMASTL1.FILE: custmastl1.lf CUSTMAST.FILE
CUSTMAST.FILE: custmast.pf
ITEMMAST.FILE: itemmast.pf
ITEMMASTL1.FILE: itemmastl1.lf ITEMMAST.FILE
ORDERITEM.FILE: orderitem.pf
ORDERITML1.FILE: orderitml1.lf ORDERITEM.FILE